name: Publish docker image

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string

    secrets:
      NPMRC:
        required: true

jobs:
  build-and-push-website:
    name: Build and push website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          secrets: |
            "npmrc=${{ secrets.NPMRC }}"
          push: true
          tags: |
            ${{ inputs.tags }}
