name: Publish production docker image

on:
  create:
    tags:
      - '*'  

jobs:
  release_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/*/}"

  publish_production_docker:
    needs: date_sha_tag
    uses: ./.github/workflows/on-demand-publish-docker-image.yml
    with:
      tags: |
        ghcr.io/wepublish/hauptstadt:${{ needs.release_version.outputs.version }}
        ghcr.io/wepublish/hauptstadt:latest
    secrets: inherit
