name: Publish main docker image

on:
  push:
    branches:
      - main

jobs:
  date_sha_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.image_tag.outputs.tag }}
    steps:
      - id: image_tag
        run: echo "::set-output name=tag::$(date +%s)-${{ github.sha }}"

  publish_main_docker:
    needs: date_sha_tag
    uses: ./.github/workflows/on-demand-publish-docker-image.yml
    with:
      tags: |
        ghcr.io/wepublish/hauptstadt:main-${{ needs.date_sha_tag.outputs.tag }}
        ghcr.io/wepublish/hauptstadt:main
    secrets: inherit
